project:
  type: website
  output-dir: docs

website:
  title: "Numbers Around Us"
  search: false
  page-footer: "For everybody, not to be fooled by numbers"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Newest articles
        href: last-articles.qmd
      - text: Challenges
        href: challenges/index.qmd
      - text: Business Intelligence
        href: bi/index.qmd
      - text: Data Science
        href: ds/index.qmd
      - text: Data Philosophy
        href: dp/index.qmd
    tools: 
      - icon: github
        text: Github
        href: https://github.com
                                                                                                                                                                                                                                                                                                                          
format:
  html:
    css: [styles.css]
    theme: 
      dark: superhero
      light: journal
    page-layout: article
    code-fold: true
    highlight-style: material-palenight
