---
title: "Tools --- you're defining them or they define you?"
author: "Numbers around us"
date: "2022-09-27"
format: html
---

Sometimes I wonder which direction is stronger. I realize that order in which I got to know each tool is really defining the way I work, my routine and way I'm developing my toolbox. As I mentioned in previous post I'm self-educated in a matter of IT and data analytics, so my way was little bit random.

Of course, first analytical tool I get to know was Excel (wider spreadsheets). Some people said that Excel is the only thing you need, that you can do virtually everything with this program. To a certain degree I would agree with this sentence. I constructed Warhammer Fantasy Roleplay Game 2 ed. character generator in Excel about 14 years ago. But it is also the most underused tools compared to number of computers where it is installed. Even in business Excel, Google Sheets and few other spreadsheets are usually used as tabular notebook and substitute for single-table database.

Spreadsheets are omnipresent, they are in almost every company, so I use Excel as well, but nowadays only purpose I prefer to use it is data exchange. I use it as data sources or way to deliver transformed data to end user.

My next step in data world is not really usual. It is Kibana. This service is a part of ELK environment. As it is not tool designed for analytics or business intelligence, so using it for this purpose was hassle. (At least 6--7 years ago. I didn't use it since then.) Visualization elements could be used to monitor sales, production using streamed data from Elastic Search precalculated database. I know that it was not the way I should work, but it was only beginning.

Then comes time of "real analytics" or BI. About 5 years ago I was fascinated with data visualisation and found Tableau. I was delighted that without knowing any programming languages and without deep knowledge of databases, one could perform analysis that is on moderate level and get interesting insights. I really appreciated these opportunities and developed myself. I met some inspiring people, I found some more complex analytics ideas, ideas for new projects. And I realized that Tableau will not be enough, that any BI Tool will not be enough to do analytics. And I not only tried Tableau, but also PowerBI, Qlik and one tool which BI Analysts would say that that is not BI, Google Data Studio.

That's why I turned my eyes to programming languages used for computing and data science: Python and R. Of course there is Scala or Stan as well nowadays, but those was my first choice. Today I would say that perfect situation would be to be bilingual, but for sake of early learning I chose R. Especially because colleagues had basics already.

Nowaday I am big R enthusiast with councious need to develop my Python skills. Last period working as analyst I would divide my time between Tableau and R in 20% to 80% ratio. With lower layer consists of SQL for almost every task and projects. What am I achieving with R:
- EDA
- further analysis
- forecasting
- modeling data
- visualize data
- produce reports
- execute ETL processes.

Next post would be zoomed and focused on one of tools mentioned above. But at the end of this I'll mention my current tech stack: Tableau, PowerBI (start-level), SQL (MySQL, MariaDB, SQL Server), R language, Python (Pandas and Numpy), and last but not least, Excel.
