---
title: "Humanist in firm grip with world of maths..."
author: "Numbers around us"
date: "2022-09-20"
format: html
---

Let my first post be a short introduction of me as a person. My life and career was not always focused on science, at least strict "mathematical" science.

My mind was open to different branches of science. As young kid I was fascinated by chemistry and astronomy. That's why I still remember latin names of several constellations. Then came period in my life when I have focused on social sciences. Being maybe little bit too young I read Hawking and Hawkins. Then historical books (like for example Norman Davies series about Europe and Poland), world's mythology and ancient and prehistory. Then came historical novels, political fiction, spy, medical and judicial thrillers. And that was all before I turned 16. I have two qualities which can be considered as blessings, but curses as well. Curiosity and exceptional (not perfect but very capable) memory. Because of this wide spectrum of interests I was not able to choose my further way, and as rather humanist I went to media studies.

Maybe it is not very humble, but because of knowing history and myself I think about myself as Renessaince man. Of course Leonardo da Vinci or Michalangello Buonarotti is far beyond my reach, but I'd like to follow their steps.

But usually (especially in Poland) occupations which are not specialized, doesn't pay well. I started working in customer service, then sales and logistics and some not really fascinating jobs, when winter came...

Really quiet winter, especially because of very harsh frost. I started to read some web development tutorials. After few weeks I made simple website, and that was an impulse... to look for some more technical job. And my adventure on borderlands of "real" IT began. After 2 years of MarTech and Marketing Automation tasks I took into world of numbers... as analyst and BI developer.

How I see this world? What tools and skills I use in everyday job? Be patient, It'll come soon.

